atari/800xl/ldscripts/link.ld
atari/800xl/lib/crt0.s

dynamically set atari stack location to MEMTOP value (0xBBFF with BASIC disabled, 0x9BFF with BASIC enabled, just below video memory)
Also remove infinite loop on the end (and return to DOS)

set atari stack location to MEMTOP

---

atari/800xl/lib/chrout.c

Current version of atari __chrout  doesn't work when inlined.

A800 chrout bugfix

---

mos-platform/common/include/new
mos-platform/common/lib/new.cc

Doing so revealed some issues  in __set_heap_limit:
1. New memory needs to be coalesced into the previous blocks, so a large allocation spanning new and old heap limits can succeed.
2. The __heap_bytes_free accounting was not correct after extending the heap limit.

Make std::set/get_new_handler work per standard.

---

mos-platform/common/include/CMakeLists.txt
mos-platform/common/include/initializer_list

This PR enables code where initializer lists are implicitly created by clang.

Initializer List

---

mos-platform/common/lib/CMakeLists.txt

it seems it is broken since https://github.com/llvm-mos/llvm-mos-sdk/commit/013411109823756c76588583a2f02fa3679fa616

fix building with cmake 3.16.3

---

mos-platform/common/include/CMakeLists.txt
mos-platform/common/include/__type_traits_impl.h
mos-platform/common/include/cstddef
mos-platform/common/include/type_traits

This is an implementation of type_traits as of c++17. 
Most of the type traits map directly to clang intrinsics, so they have simple definitions.
The more complex template meta programs are simplified versions of the libc++ definitions. The primary differences are removing support for non-clang compiler and pre-c++17 variants.

Type Traits Implementation

---

mos-platform/osi-c1p/CMakeLists.txt
mos-platform/osi-c1p/crt0.s
mos-platform/osi-c1p/getchar.c
mos-platform/osi-c1p/kbhit.s
mos-platform/osi-c1p/link.ld

This is the implementation of getchar() for the osi-c1p target. It is based on the cc65 implementation for reading the keyboard, which in turn was inspired by the original ROM routine of the Ohio Scientific Challenger 1P machine.

getchar() implementation for osi-c1p target

---

mos-platform/dodo/link.ld

Before this change, linking could fail with
```
ld.lld: error: undefined symbol: __zp_bss_size
```

Add zp.ld to dodo's linker script

---

mos-platform/dodo/api.h

None of the functions in the dodo api can call anything from the main
LTO unit, so annotate all of them.
Closes #62
See https://github.com/llvm-mos/llvm-mos/issues/210

Add __attribute__((leaf)) to dodo api functions

---

mos-platform/dodo/link.ld

Previously the initial value of memory in the zero page data section was not
included in the output file for dodo, and not copied to the zero page.

Load .zp.data from fram for dodo

---

mos-platform/mega65/clang.cfg

The 65ce02 is currently the closest match to the derived GS4510 used in the mega65.

Add CPU definition to mega65 target

---

mos-platform/c64/CMakeLists.txt
mos-platform/c64/link.ld
mos-platform/c64/unmap-basic.S
utils/elftocpm65/elf.h

On the C64, there is very little reason to keep the BASIC ROM mapped when executing machine code. Switching out the BASIC ROM frees up $A000-$BFFF, and opens up contiguous access to the $C000-$CFFFF area for a total of 12KB of additional RAM.
In the future it would be nice to also have a configuration option to switch out the KERNAL ROM ($E000-$FFFF) and reimplement the KERNAL routines in software so you only use what you need.

[C64] Increase available RAM to 50KB by swapping out BASIC ROM

---

mos-platform/common/include/limits

See #57.
This is incomplete yet, but should work for all typical uses.
The standard defines `std::numeric_limits` for all default-constructible types. This makes no sense for me, but I'll make it standard-compliant later.
I understand that `float` and `double` are out of scope.

Add <limits> for integral types.

---

mos-platform/common/include/algorithm
mos-platform/common/include/array
mos-platform/common/include/iterator
mos-platform/common/include/utility

This reduces the list of errors in #52 to:
C:\0\a8\llvm>"install\bin\mos-c64-clang++.bat" -Os -Wall pong.cpp
pong.cpp:260:19: error: no member named 'make_tuple' in namespace 'std'
return std::make_tuple(
~~~~~^
pong.cpp:295:31: error: no matching constructor for initialization of 'const std::array<Color, 16>'
const std::array<Color, 16> colors = {{
^        ~~
C:/0/a8/llvm/install/bin/../mos-platform/common/include/array:9:8: note: candidate constructor
(the implicit copy constructor) not viable: cannot convert initializer list argument to 'const
std::array<(anonymous namespace)::Color, 16>'
struct array {
^
C:/0/a8/llvm/install/bin/../mos-platform/common/include/array:9:8: note: candidate constructor
(the implicit move constructor) not viable: cannot convert initializer list argument to …

Start implementations of <algorithm>, <array>, <iterator>, <utility>

---

mos-platform/commodore/CMakeLists.txt
mos-platform/commodore/cbm_k_chkin.s
mos-platform/commodore/cbm_k_ckout.c
mos-platform/commodore/cbm_k_ckout.s
mos-platform/commodore/cbm_k_load.s
mos-platform/commodore/cbm_k_open.c
mos-platform/commodore/cbm_k_open.s
mos-platform/commodore/cbm_k_save.s

When the Commodore OPEN kernal routine returns with the carry flag clear, the OPEN should be treated as a success and the value of the accumulator disregarded. Previously, this was not implemented correctly. Now, if carry flag is clear on return from OPEN, 0 is returned to the caller of `cbm_k_open()` indicating a success. 
Thanks to @mlund for finding this (#99)

Fix bug in cbm_k_open function

---

mos-platform/cpm65/link.ld

This is fallout from #106; turns out that LOADADDR() addresses are absolute. This meant that any address sourced from LOADADDR() doesn't get relocated, even when they should be. Specifically, this was causing the source for the initialised zero page to be read from the wrong location.
The solution is to use a pointer difference of LOADADDRs from the start of the binary to get the offset, and then add on the ADDR of the binary start, turning the symbol into a .text address.

Fix a bug in the cpm65 linker script causing certain addresses not to be relocated.

---

mos-platform/common/c/ctype.c
mos-platform/common/c/string.c
mos-platform/common/include/ctype.h
mos-platform/common/include/string.h
mos-platform/cpm65/CMakeLists.txt
mos-platform/cpm65/cpm-wrappers.c
mos-platform/cpm65/cpm.S
mos-platform/cpm65/cpm.h
mos-platform/cpm65/link.ld
mos-platform/cpm65/parsefcb.c

This:
- fixes a bug in the CPM65 headers where one function would corrupt the parameters when called
- updated with some new CPM65 functionality
- added a `cpm_parse_filename` helper function (in pure C)
- adds `isalnum` and `isspace` to ctype
- adds `strrev`, `strspn`, `strpbrk` and `strtok` to strings

Update CPM65; add some missing ctype and string functions

---

mos-platform/rpc8e/link.ld

RedPower 2, due to a bug, will only properly process binary files aligned up to the nearest 128-byte boundary.
This wasn't spotted in the initial PR, as the tool I used to write binaries to the game world's save data automatically took care of such alignment for me - however, [a different user](https://twitter.com/chaoticCharacte/status/1670145998264360961), utilizing a different file upload approach, ran into this bug.

[RPC8/e] Fix output binary padding.

---

mos-platform/atari8/init-stack.S
mos-platform/c64/link.ld
mos-platform/cx16/link.ld
mos-platform/mega65/link.ld
mos-platform/nes-mmc1/c-in-prg-ram-0.ld
mos-platform/nes/c-in-ram.ld
mos-platform/osi-c1p/link.ld
mos-platform/pet/link.ld
mos-platform/rpc8e/init-stack.S

The intended value of the soft stack pointer is the byte *after* the top-most (last) writable byte in the stack area. This matches the convention used by targets "dodo" and "sim"; therefore, this commit fixes it for all other targets.

Unify soft stack initialization.

---

mos-platform/cx16/imag-regs.ld

I got caller-saved and callee-saved registers mixed up for this part.
Leaving to @XarkLabs to verify that I'm not missing something else - it's not a platform I work with regularly, or at all...

[CX16] Fix imaginary register layout.

---

mos-platform/commodore/cbm_kernal.inc

Typo causing build issues on X16 etc.

fix #elseif typo causing wrong define

---

mos-platform/cx16/cx16.h

Fix Commander X16 header `cx16.h` to work with C++.

Fix cx16.h for c++

---

mos-platform/commodore/CMakeLists.txt
mos-platform/commodore/cbm.h
mos-platform/commodore/cbm_k_rdtim.s

Add cbm-K-rdtim kernal call to return 24-bit "jiffy clock".

add cbm-K-rdtim commodore kernal call

---

mos-platform/commodore/cbm_k_load.s

Bug fix.  Since return type changed to void * from unsigned int, error return needs fixing to return in __rc2 also.

fix error return to use __rc2

---

mos-platform/mega65/clang.cfg

The c64 headers are useful also on mega65 which for example also has VIC2 and SID chips.

Add C64 include paths to mega65 target

---

mos-platform/eater/crt0/serial.S
mos-platform/eater/crt0/systick.S

Clean up the eater platform port.  The local labels in the .S file were being marked as global by the assembler because I forgot to prefix them with ".L".

Make local asm labels actually local in the eater platform

---

mos-platform/eater/crt0/systick.S

Fix a bug in the intialization of T2 in the eater backend's systick code.  I was loading 0 into A to store into VIA_ACR but wasn't actually storing it.  It probably "just worked" because the register's value at reset time is 0 anyway, but best to be clean about it.

Fix initialization of T2 in eater systick code

---

utils/pce-mkcd/pce-mkcd.cc

This file used std::function without including the <functional> header and fails to compile on VS2022

Fix MSVC compile error with pce util

---

mos-platform/nes-action53/_prg-rom-banked.ld
mos-platform/nes-action53/bank.s
mos-platform/nes-action53/reset.s
mos-platform/nes-mmc1/bank.s
mos-platform/nes/famitone2/famitone2.s
mos-platform/nes/neslib/neslib.s

Two bug fixes
* Add explicit NMI ordering for all of the NES target mappers with NMI callbacks. This fixes an issue where the neslib nmi isn't guaranteed to be last (which can cause all sorts of problems when it starts doing VRAM updates during the main gameplay)
* Fixes an issue where banking would not take effect because the PRG bank size wasn't set in the reset routine. The also defaults the mirroring mode to VERTICAL (but its easy enough for users to change)

Fix a few Action 53 bugs

---

mos-platform/nes/rompoke/misc/generate-rompoke-table-linkscript.lua
mos-platform/nes/rompoke/rompoke-table.ld

It appears that `FILL()` *has* to be four bytes to work consistently. This is because GNU defines the value inside it as 4-byte *big*-endian.
The PR amends this and adds an explanatory note to the link script.

NES: Fix bus conflict ROM poke table generation

---

examples/CMakeLists.txt
examples/struct-of-arrays.cc
mos-platform/common/include/soa-struct.inc
mos-platform/common/include/soa.h

This adds two new types to the SDK under `soa.h`:
- `soa::Array<T, s>` is an array of `T` of size `s`, but where the k'th byte of each `T` are stored contiguously.
- `soa::Ptr<T>` is a pointer to an element of `soa::Array`.
The include-eable `soa-struct.h` specializes `soa::Ptr<T>` for a struct type, including its members as distinct `soa::Ptr<T>` instances that point to the members.
Using this library allows global arrays of structs to be accessed using the absolute indexed addressing mode if it's always known at compile-time what portion of the struct is being accessed. This is generally true if there are no pointers into the array; in that common case, using this library can produce a huge speedup.
See the included example for more details; the library is quite expansive in practice, …

Add C++ struct-of-arrays library and example

---

mos-platform/nes-cnrom/bank.c
mos-platform/nes-cnrom/bank.h
mos-platform/nes-unrom-512/CMakeLists.txt
mos-platform/nes-unrom-512/bank.c
mos-platform/nes-unrom-512/bank.h
mos-platform/nes-unrom-512/bank.s
mos-platform/nes-unrom-512/common.ld
mos-platform/nes-unrom/bank.c
mos-platform/nes-unrom/common.ld
test/nes-cnrom/CMakeLists.txt
test/nes-cnrom/chr-swap-split.c
test/nes-unrom-512/CMakeLists.txt
test/nes-unrom-512/chr-swap-split.c
test/nes-unrom-512/no-compile/CMakeLists.txt
test/nes-unrom-512/no-compile/chr-rom-too-big.c
test/nes-unrom-512/no-compile/prg-rom-too-big.c

Fixes https://github.com/llvm-mos/llvm-mos-sdk/issues/195 for these three mappers. I *think* this leaves only MMC3 as the remaining mapper without NMI handling (MMC1 and Action53 already had their own; NROM does not require it).
I've implemented my own approach to handling NMIs:
* _BANK_SHADOW is always written to before the mapper's MMIO register itself;
* _BANK_SHADOW is written to MMIO at an early stage of NMI, allowing developer-side consistency for NMI code written in C once the AXY calling convention is added.
For CNROM and UNROM-512, I've extended this with additional functionality:
* The graphical part of the register (CHR bank, mirroring) is now deliberately separated between "shadow" (written to the MMIO register on NMI or on user request) and the MMIO register.
* Writing to the …

NES: Rework CNROM, UNROM and UNROM-512 to properly handle NMIs.

---

mos-platform/atari8-common/clang.cfg

Per `link.ld`, the Atari 8-bit computers' available zero page encompasses the area of `0x80` to `0xFF`, which is 128 bytes - subtracting the 32 bytes for registers, that's 96 bytes, not 206 bytes.

atari8-common: Fix clang.cfg available zero page size

---

mos-platform/atari8-common/CMakeLists.txt
mos-platform/atari8-common/charset.h
mos-platform/c64/charset.h
mos-platform/cx16/CMakeLists.txt
mos-platform/cx16/charset.h
mos-platform/pet/charset.h

Fixes https://github.com/llvm-mos/llvm-mos-sdk/issues/162 ; fixes https://github.com/llvm-mos/llvm-mos-sdk/issues/160 ; also consistently handles non-prefixed and lowercase-`u`-prefixed strings in atari8 and c64 targets, as the compiler-given error can be somewhat unintuitive otherwise.

atari8, cx16: Add charset support.

---

mos-platform/nes-mmc1/bank.c
mos-platform/nes-mmc1/bank.h
mos-platform/nes-mmc1/bank.s
mos-platform/nes-mmc1/common.ld
test/nes-mmc1/chr-rom.c
test/nes-mmc1/prg-ram-c.c
test/nes-mmc1/prg-ram.c

This makes the interface for banking on MMC1 more consistent with the other mappers.
- Removed direct access to shadow registers, replacing it with getter functions where required. These values may need to be computed on some mappers, so using functions allows the interfaces to look more similar across mappers. Inlining should completely fold this away.
- Added accessors for the high part of the CHR bank. On some MMC1 boards, this controls PRG-RAM/ROM state, so it must be visibile to allow saving/restoring that state.
- Replaced the retry versions of chr bank setters with ones that reliably control just the high bits. The retry versions were always intended just to control the high bits; this makes this explicit and separate from true CHR bank control.
- The "set" functions that affect …

[Breaking] Rework MMC1 banking.

---

mos-platform/cx16/cx16.h

No comments on the registers, because they're quite complicated

Added VERA FX registers to cx16.h

---

mos-platform/nes/nesdoug/nesdoug.s
mos-platform/nes/neslib/neslib.s

For a single 3-byte horizontal operation this saved 14 cycles from `flush_vram_update2`
With two `multi_vram_buffer_vert` operations totaling 36 tiles and 10 `one_vram_buffer` this saved 44 cycles. This looks like it works out to ~12 cycles per multi and 2 cycles per single.

Improve NMI performance for multi_vram_buffer ops

---

utils/common/elf-mos.h

See https://github.com/llvm-mos/llvm-mos/issues/358 for more information.

utils: Fix elf-mos.h for compatibility with ELF specification 0.3.0.

---

mos-platform/nes/nesdoug/CMakeLists.txt
mos-platform/nes/nesdoug/vram_buffer.c
mos-platform/nes/nesdoug/vram_buffer.s
mos-platform/nes/nesdoug/vram_buffer_ops.s
mos-platform/nes/neslib/oam_update.c
mos-platform/nes/neslib/oam_update.s
mos-platform/nes/neslib/pal_update.c
mos-platform/nes/neslib/pal_update.s

Fixes #215:
- Use weak symbols
- Move PAL_BUF out of hardware stack

Improve allocation of VRAM/PAL/OAM buffers

---

mos-platform/cpm65/link.ld
utils/elftocpm65/elftocpm65.cc

This fixes the following problems:
- relocations in `.data` segments weren't being processed
- IMM8 relocations were being ignored

[CP/M-65] Fix some problems with relocation conversion.

---

mos-platform/common/ldscripts/bss-sections.ld
mos-platform/common/ldscripts/data-sections.ld
mos-platform/common/ldscripts/noinit-sections.ld
mos-platform/common/ldscripts/rodata-sections.ld
mos-platform/common/ldscripts/text-sections.ld
mos-platform/common/ldscripts/zp-noinit-sections.ld

This allows seamless ca65 integration without altering default platform linker scripts.
See llvm-mos/llvm-mos#395

Add default cc65 segments

---

mos-platform/atari2600-3e/mapper.h
mos-platform/atari2600-3e/mapper_3e.c
mos-platform/atari2600-4k/mapper.h
mos-platform/atari2600-common/CMakeLists.txt
mos-platform/atari2600-common/mapper_macros.h
mos-platform/atari2600-common/mapper_xram_single.h
mos-platform/atari2600-common/vcs.ld

- Fixed zp section overlapping registers.
- Fixed bank selection macros to accept macro parameters.
- Better Stella signature.

Atari2600 bug fixes

---

.github/workflows/package.yml

More fixes for #240 to build for arm64

Add x86_64 and arm64 build targets for macOS

---

mos-platform/common/c/printf.c

There should only be one printf routine present given its size, but the
inliner may inline the implementation into multiple different versions
of the function. Explicitly basing the routines on one another
discourages this.

Base printf routines on one another

---

mos-platform/common/c/cxa-atexit.cc
mos-platform/common/c/stdlib.cc

atexit should only be brought in if directly referenced, by calloc can
be a libcall in some circumstances. Accordingly, move atexit out of
stdlib.cc (with calloc) into cxa-atexit.cc.

Move atexit to cxa-atexit.cc

---

.github/workflows/package.yml
CMakeLists.txt
test/CMakeLists.txt
test/atari2600-common/test.cmake
test/mesen.lua
test/nes-cnrom/chr-swap-split.c
test/nes-cnrom/mesen.lua
test/nes-cnrom/test-lib.c
test/nes-gtrom/CMakeLists.txt
test/nes-gtrom/chr-swap-split.c
test/nes-gtrom/mesen.lua
test/nes-mmc1/mesen.lua
test/nes-mmc1/test-lib.c
test/nes-nrom/mesen.lua
test/nes-unrom-512/CMakeLists.txt
test/nes-unrom-512/chr-swap-split.c
test/nes-unrom-512/mesen-workaround.s
test/nes-unrom-512/mesen.lua
test/nes-unrom/mesen.lua
test/test-lib-mesen.c
test/test.cmake

This improves the SDK test suite, fixing flakiness issues and working around a
Mesen bug. Accordingly, this allows us to depend entirely upon libretro and
emutest; the Mesen Lua tests have been removed. This allows us to simplify our
test setup, since we can now work entirely off of cores fetched from libretro
builders.
- Remove old test libs
- Remove plain mesen tests
- Remove FCEUMM core
- Allow Arch stella package
- Workaround Mesen UNROM-512 bug
- Update stella test CRC
- Fix chr-swap-split test flake
- Download libretro cores from nightly buildbots

Fix SDK test suite

---

README.md

This will be restored when the target is updated.

Remove reference to unmerged Atari 8-bit MegaCart target

---

test/nes-nrom/no-compile/chr-ram-too-big.c
test/nes-nrom/no-compile/chr-rom-non-pow2.c
test/nes-nrom/no-compile/chr-rom-too-big.c
test/nes-nrom/no-compile/prg-ram-too-big.c
test/nes-nrom/no-compile/prg-rom-too-big.c

nrom doesn't have mapper.h, use ines.h

fix nes-nrom "no-compile" tests to fail for the right reasons

---

mos-platform/atari8-mega/link.ld

Explicitly separate bank0 from the the fixed region.  This means code and data that is marked for bank0 will not be in the common fixed area and only accessible from bank0.

Atari 8-bit MegaCart, separate 'fixed' and 'bank0'

---

test/atari8-stdcart/compile/CMakeLists.txt
test/atari8-stdcart/compile/cart-rom-16-fit-14.c

@mysterymath this should work (lacked const earlier)

[atari8-stdcart] test; 16 KiB ROM fit 14 KiB of RODATA

---

mos-platform/common/c/CMakeLists.txt
mos-platform/common/c/malloc.cc
mos-platform/common/c/stdlib.cc
mos-platform/common/include/stdlib.h
mos-platform/common/ldscripts/noinit-sections.ld

This uses Knuth boundary tags to allow constant-time coalescing. The
allocator remains first fit, but with this implementation, all of the
O(n) loops have been removed except for the scan for first fit, which
can exit early.
The free list has been altered to search for chunks in FIFO order; from
Wilson's survey, this is an excellent strategy compared to other simple
approaches, since it maximizes the amount of time a chunk is available
to be coalesced. This minimizes fragmentation, which increases the
expected speed of the first fit scan.
A typical boundary tag implementation requires a boolean tag on each
chunk indicating whether the previous chunk is free. We do this the
usual way: chunks are aligned to 2, and the prev_free tag is the LSB of
the size.
The minimum allocation size remains …

Rewrite malloc

---

mos-platform/rp6502/rp6502.h
mos-platform/rp6502/xregn.c

Sorry about the warning. Not sure how I missed it.

remove va_start warning from rp6502 xregn

---

mos-platform/atari8-common/putchar.c

Doing this ensures we get output when HATABS is updated as is the case for 80-column adapters.

[atari8-common] Use HATABS for __putchar

---

mos-platform/rp6502/rp6502.h

add CPP extern "C" to rp6502.h

---

mos-platform/common/ldscripts/noinit-sections.ld

In the GNU linker language, `ALIGN(alignment)` actually produces an absolute value, while `ALIGN(address, alignment)` produces a relocatable value. See https://sourceware.org/binutils/docs/ld/Builtin-Functions.html#index-ALIGN_0028align_0029 which states that the first is equivalent to `ALIGN(ABSOLUTE(address), alignment)`. Wheee!
This causes `__heap_start` on CP/M-65 to be an absolute value rather than a relocatable one, _even though it's defined in a relocatable segment_, which meant the heap address wasn't getting relocated to the right place, causing big chunks of the program to be overwritten --- with different results on each target platform because they each loaded binaries in different places...

Make __heap_start relocatable rather than absolute.

---

mos-platform/cpm65/clang.cfg

This works around the elftocpm65 bug described in #320, at least partially.

Disable ZP LTO on CP/M-65

---

mos-platform/supervision/supervision.c
mos-platform/supervision/supervision.h

Technically a breaking change (though nobody uses the target yet), so it would be a good idea to get it in before the next release.
It probably makes more sense this way, but leads to an annoying `sv_lcd_init(); / sv_lcd_clear(); / sv_lcd_enable();` chain in `main()`, if you want to use the LCD, which is a very likely scenario given this is a handheld game console. Maybe it would be a better idea to add an `sv_lcd_init();` call to crt0?

[Breaking] [supervision] Split sv_lcd_init and sv_lcd_enable.

---

mos-platform/mega65/_45E100.h

The size of the ethernet controller struct should be 15 bytes.

[mega65] Fix assertion of ethernet controller struct

---

mos-platform/commodore/CMakeLists.txt

We currently take advantage of the BASIC ZP area, but commodore family
targets can only load programs from a BASIC environment. This makes it
intrinsically unsafe to exit by return, since it always returns to a
possibly-clobbered environment.
Instead, exiting by looping still allows a screen's worth of output to
be viewed, without possibly returning to a broken BASIC interpreter.
This is arguably a bugfix, but it's also a very significant change in
behavior, so I'm considering it a breaking change.
We should also have an optional library that saves and restores BASIC ZP
on entry-exit and exits via returning, but that shouldn't block this
change.

[Breaking] Make commodore family targets infinitely loop on exit

---

mos-platform/neo6502/link.ld

Tweak the neo6502 link script to output the .neo file format.
Also took the opportunity to lower the start address to 0x200 -  I'm pretty sure everything after the zeropage and 6502 stack page is far game on the neo6502.

neo6502: Output .neo file format (#344)

---

mos-platform/common/c/stdio-full.c

Fix `fopen(filename, "a")` misinterpreted as `fopen(filename, "w")`

---

mos-platform/common/c/stdio-full.c

While this was probably harmless because we are single-threaded, the allocator could generally store its internal structure in the freed block.

Fix use after free in `_stdio_closeall`

---

mos-platform/common/c/string.c

Hi,
I traced back a misbehaving qe (editor in CP/M-65) to strtok() not working correctly, which in turn turned out to be strpbrk(). This fixes that and also results in a slightly smaller binary.
Regards,
Ivo

Fix strpbrk()

---

mos-platform/nes/crt0.c
mos-platform/supervision/crt0.c

Useful in cases where custom init is needed.

nes/supervision: Add weak attribute to early and late init

---

mos-platform/neo6502/api/controller.c

file: `mos-platform/neo6502/api/controller.c` [link](https://github.com/llvm-mos/llvm-mos-sdk/blob/main/mos-platform/neo6502/api/controller.c)
function:` uint8_t neo_controller_read(uint8_t index)`
bug 1: return type should be `uint32_t`
bug 2: `index` is not placed in `ControlPort.params[0]` before the API is invoked.

Neo6502 platform API: controller status API
